name: xxtea
version: 2.0.0
author: Ma Bingyao <mabingyao@gmail.com>
description: XXTEA for Dart
homepage: https://github.com/xxtea/xxtea-dart
environment:
  sdk: '>=2.0.0 <3.0.0'
dev_dependencies:
  test: 'any'
